os: linux
dist: focal
group: edge
language: python
python:
  - "3.8"
script:
  - pytest  # Adjust this command according to your project's testing framework
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main
